In [1]:
import pandas as pd

In [12]:
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(os.getcwd()).resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

print(os.getcwd())

/Users/daniehbenotman/Desktop/worldbank_tableau_project/notebooks

In [14]:
os.chdir("/Users/daniehbenotman/Desktop/worldbank_tableau_project")
print("✅ Working directory changed to:", os.getcwd())

✅ Working directory changed to: /Users/daniehbenotman/Desktop/worldbank_tableau_project

In [2]:
wb = pd.read_csv("../data/updated_countries.csv")
wb.head()

,year,value,country_id,country_name,indicator_id,indicator_name,unit_type
0,2024,NaN,AE,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
1,2023,1.0,AE,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
2,2022,1.0,AE,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
3,2021,1.0,AE,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
4,2020,1.0,AE,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)

In [6]:
unesco = pd.read_csv("../data/UNESCO.csv",sep=";")
unesco.head()

,indicator_code,indicator_name,country_code,country_name,year,value
0,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2005,"59,84999847"
1,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2017,"64,56999969"
2,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2018,"65,54000092"
3,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2019,"71,30999756"
4,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2021,"73,12000275"

In [7]:
unesco.rename(columns={"country_code":"country_id","indicator_code":"indicator_id"}, inplace=True)

In [10]:
unesco.head()

,indicator_id,indicator_name,country_id,country_name,year,value
0,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2005,"59,84999847"
1,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2017,"64,56999969"
2,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2018,"65,54000092"
3,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2019,"71,30999756"
4,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2021,"73,12000275"

In [15]:
from src.unit_types import add_unit_types

unesco= add_unit_types(unesco, column="indicator_name")
unesco.head()

,indicator_id,indicator_name,country_id,country_name,year,value,unit_type
0,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2005,"59,84999847",Percent (%)
1,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2017,"64,56999969",Percent (%)
2,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2018,"65,54000092",Percent (%)
3,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2019,"71,30999756",Percent (%)
4,EA.3T8.AG25T99.F,"Educational attainment rate, completed upper s...",ARE,United Arab Emirates,2021,"73,12000275",Percent (%)

In [16]:
# Remove UNESCO country_id because it will confuse merges
unesco = unesco.drop(columns=["country_id"])

In [17]:
wb = wb.drop(columns=["country_id"])

In [18]:
combined = pd.concat([wb, unesco], ignore_index=True)

In [19]:
combined.head()

,year,value,country_name,indicator_id,indicator_name,unit_type
0,2024,NaN,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
1,2023,1.0,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
2,2022,1.0,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
3,2021,1.0,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)
4,2020,1.0,United Arab Emirates,SG.APL.PSPT.EQ,A woman can apply for a passport in the same w...,Binary (1/0)

In [21]:
combined.to_csv("data/merged_data.csv", index=False)